const balanceOrder=["kilo-credit","openai-api-credit","claude-usage-credit","claude-api-credit"];
const quotaOrder=["chatgpt-weekly","claude-session","claude-weekly","claude-fable","claude-usage-cap"];
const $=id=>document.getElementById(id);
let collectedAt=null;
function renderUpdated(){if(!collectedAt){$("updated").textContent="No local snapshot yet";return}const age=Math.max(0,Math.floor((Date.now()-new Date(collectedAt).getTime())/1000));const minutes=Math.floor(age/60);const seconds=age%60;const elapsed=minutes>=60?`${Math.floor(minutes/60)}h ${minutes%60}m ago`:`${minutes}m ${seconds}s ago`;$("updated").textContent=`Updated ${new Date(collectedAt).toLocaleTimeString([], {hour:"numeric",minute:"2-digit"})} - ${elapsed}`}
function render(metrics=[]){const byKey=Object.fromEntries(metrics.map(metric=>[metric.key,metric]));$("balances").innerHTML=balanceOrder.map(key=>{const m=byKey[key];return `<article class="card provider-link" data-key="${key}" tabindex="0" role="button" title="Open ${m?.provider??"provider"}"><div class="card-top"><span>${m?.provider??"Awaiting provider"}</span><button class="card-refresh" data-key="${key}" type="button" title="Refresh ${m?.provider??"provider"}" aria-label="Refresh ${m?.provider??"provider"}">↻</button></div><strong>${m?.display??"—"}</strong></article>`}).join("");$("quotas").innerHTML=quotaOrder.map(key=>{const m=byKey[key];return m?`<article class="quota provider-link" data-key="${key}" tabindex="0" role="button" title="Open ${m.provider}"><div class="quota-top"><div><span>${m.provider} · ${m.label}</span>${m.resetText?`<small>${m.resetText}</small>`:""}</div><strong>${m.display} remaining</strong></div><div class="meter" aria-label="${m.label}: ${m.display} remaining"><i style="width:${Math.max(0,Math.min(100,m.value))}%"></i></div></article>`:""}).join("");document.querySelectorAll(".provider-link").forEach(item=>{item.addEventListener("click",event=>{if(!event.target.closest(".card-refresh"))focusProvider(item.dataset.key)});item.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();focusProvider(item.dataset.key)}})});document.querySelectorAll(".card-refresh").forEach(button=>button.addEventListener("click",()=>refreshProvider(button)))}
async function focusProvider(key){$("status").textContent="OPENING";const result=await chrome.runtime.sendMessage({type:"focus-provider",key});if(!result?.ok){$("status").textContent="CHECK TABS";$("updated").textContent=result?.error??"Unable to open provider";$("updated").className="error"}}
async function load(){const data=await chrome.storage.local.get(["latestMetrics","lastCollectedAt","lastIssues","closeOpenedTabs","autoCollectionEnabled"]);render(data.latestMetrics);$("issues").textContent=(data.lastIssues??[]).join(" ");$("close-opened-tabs").checked=Boolean(data.closeOpenedTabs);$("auto-updates").checked=data.autoCollectionEnabled!==false;collectedAt=data.lastCollectedAt??null;renderUpdated();$("status").textContent=data.lastCollectedAt?(data.lastIssues?.length?"UPDATING":"READY"):"WAITING"}
async function refreshProvider(button){button.disabled=true;$("status").textContent="SYNCING";const result=await chrome.runtime.sendMessage({type:"collect-provider",key:button.dataset.key});await load();if(!result?.ok){const savedLocally=result?.error?.includes("local snapshot was saved");$("status").textContent=savedLocally?"SAVED LOCAL":"CHECK TABS";$("updated").textContent=result?.error??"Collection failed";$("updated").className=savedLocally?"":"error"}else if(result.issues?.length){$("status").textContent="UPDATING";$("updated").textContent="Kept verified values · retrying automatically"}else{$("status").textContent="SENT";renderUpdated()}}
$("auto-updates").addEventListener("change",event=>chrome.storage.local.set({autoCollectionEnabled:event.target.checked}));
$("close-opened-tabs").addEventListener("change",event=>chrome.storage.local.set({closeOpenedTabs:event.target.checked}));
$("settings").addEventListener("click",()=>chrome.runtime.openOptionsPage());
chrome.storage.onChanged.addListener((changes,area)=>{if(area==="local"&&["latestMetrics","lastCollectedAt","lastIssues","autoCollectionEnabled"].some(key=>changes[key]))load()});
$("collect").addEventListener("click",async()=>{const button=$("collect");button.disabled=true;button.textContent="Collecting";$("status").textContent="SYNCING";const result=await chrome.runtime.sendMessage({type:"collect"});await load();if(!result?.ok){const savedLocally=result?.error?.includes("local snapshot was saved");$("status").textContent=savedLocally?"SAVED LOCAL":"CHECK TABS";$("updated").textContent=result?.error??"Collection failed";$("updated").className=savedLocally?"":"error"}else if(result.issues?.length){$("status").textContent="UPDATING";$("updated").textContent="Kept verified values · retrying automatically"}else{$("status").textContent="SENT";renderUpdated()}button.disabled=false;button.textContent="Collect now"});setInterval(renderUpdated,1000);load();
